/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2017 © yangxiaobing, 873559947@qq.com
 *
 * This file is part of contentManagerSystem.
 * contentManagerSystem is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * contentManagerSystem is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with contentManagerSystem.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 这个文件是contentManagerSystem的一部分。
 * 您可以单独使用或分发这个文件，但请不要移除这个头部声明信息.
 * contentManagerSystem是一个自由软件，您可以自由分发、修改其中的源代码或者重新发布它，
 * 新的任何修改后的重新发布版必须同样在遵守GPL3或更后续的版本协议下发布.
 * 关于GPL协议的细则请参考COPYING文件，
 * 您可以在contentManagerSystem的相关目录中获得GPL协议的副本，
 * 如果没有找到，请连接到 http://www.gnu.org/licenses/ 查看。
 *
 * - Author: yangxiaobing
 * - Contact: 873559947@qq.com
 * - License: GNU Lesser General Public License (GPL)
 * - source code availability: http://git.oschina.net/yangxiaobing_175/contentManagerSystem
 */
package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.AnnouncementInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 公告信息DAO
 *
 * @author yangxiaobing
 * @date   2017/9/1
 *
 */
@Mapper
public interface AnnouncementInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int deleteByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int insert(AnnouncementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int insertSelective(AnnouncementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    AnnouncementInfo selectByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int updateByPrimaryKeySelective(AnnouncementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int updateByPrimaryKey(AnnouncementInfo record);



    /**
     * 查询站内公告总记录数
     * @param annInfo 公告实体
     * @return
     */
    Long selectCountAnnouncementInfo(AnnouncementInfo annInfo);

    /**
     * 公告信息分页列表展示分页列表显示
     * @param annInfo 公告实体
     * @return
     */
    List<AnnouncementInfo> selectAnnouncementInfoListByPage(AnnouncementInfo annInfo);
    /**
     * 根据userId查询未读公告集合
     * @param userId 用户Id
     * @return
     */
    List<AnnouncementInfo> selectUnreadAnnInfoListByUserId(@Param("userId") Integer userId);

    /**
     * 根据userId查询已读公告集合
     * @param userId 用户Id
     * @return
     */
    List<AnnouncementInfo> selectReadAnnInfoListByUserId(@Param("userId") Integer userId);

    /**
     * 查询全部公告集合
     * @return
     */
    List<AnnouncementInfo> selectAllReadAnnInfoListByUserId();

    /**
     * 根据userId查询未读公告记录数
     * @param userId 用户Id
     * @return
     */
    Long selectUnreadAnnInfoCountByUserId(@Param("userId") Integer userId);


    /**
     * 根据userId查询已读公告记录数
     * @param userId 用户Id
     * @return
     */
    Long selectReadAnnInfoCountByUserId(@Param("userId") Integer userId);

    /**
     * 查询全部公告记录数
     * @return
     */
    Long selectAllReadAnnInfoCount();

}