package com.yxb.cms.dao;


import com.yxb.cms.domain.vo.Resource;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 菜单资源DAO
 * 
 * @date   2016年8月15日 下午5:22:59
 * @author yangxiaobing@tomstaff.com
 *
 */
@Mapper
public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int deleteByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    void insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    Resource selectByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int updateByPrimaryKey(Resource record);


    /**
     * 资源信息COUNT
     * @param resource 资源实体
     * @return
     */
    Long selectCountResource(Resource resource);
    /**
     * 资源信息分页列表显示
     * @param resource 资源实体
     * @return
     */
    List<Resource> selectResourceListByPage(Resource resource);
    
}