package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.Role;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


/**
 * 角色DAO
 *
 * @author yangxiaobing
 * @date 2017/7/24
 */
@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int updateByPrimaryKey(Role record);


    /**
     * 查询角色总记录数
     * @param role 角色实体
     * @return
     */
    Long selectCountRole(Role role);
    /**
     * 角色信息分页列表显示
     * @param role 角色实体
     * @return
     */
    List<Role> selectRoleListByPage(Role role);

}