package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.UserRole;
import org.apache.ibatis.annotations.Mapper;



/**
 * 用户角色DAO
 *
 * @author yangxiaobing
 * @date   2017/7/24
 *
 */
@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    UserRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int updateByPrimaryKey(UserRole record);
}