/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2017 © yangxiaobing, 873559947@qq.com
 *
 * This file is part of contentManagerSystem.
 * contentManagerSystem is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * contentManagerSystem is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with contentManagerSystem.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 这个文件是contentManagerSystem的一部分。
 * 您可以单独使用或分发这个文件，但请不要移除这个头部声明信息.
 * contentManagerSystem是一个自由软件，您可以自由分发、修改其中的源代码或者重新发布它，
 * 新的任何修改后的重新发布版必须同样在遵守GPL3或更后续的版本协议下发布.
 * 关于GPL协议的细则请参考COPYING文件，
 * 您可以在contentManagerSystem的相关目录中获得GPL协议的副本，
 * 如果没有找到，请连接到 http://www.gnu.org/licenses/ 查看。
 *
 * - Author: yangxiaobing
 * - Contact: 873559947@qq.com
 * - License: GNU Lesser General Public License (GPL)
 * - source code availability: http://git.oschina.net/yangxiaobing_175/contentManagerSystem
 */
package com.yxb.cms.domain.vo;
/**
 * 数据清洗实体
 * @author yangxiaobing
 * @date  2017/9/18
 *
 */
public class DataCleaning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private String dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_id
     *
     * @return the value of cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_id
     *
     * @param dataId the value for cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_type
     *
     * @return the value of cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_type
     *
     * @param dataType the value for cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_time
     *
     * @return the value of cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public String getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_time
     *
     * @param dataTime the value for cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataTime(String dataTime) {
        this.dataTime = dataTime == null ? null : dataTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_count
     *
     * @return the value of cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataCount() {
        return dataCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_count
     *
     * @param dataCount the value for cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataCount(Integer dataCount) {
        this.dataCount = dataCount;
    }
}