package com.yxb.cms.domain.vo;


import java.io.Serializable;
import java.util.Date;

/**
 * 用户信息实体
 *
 * @author yangxiaobing
 * @date 2017/7/10
 */
public class User implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.user_id
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.user_login_name
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.user_name
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.user_password
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.user_status
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private Long userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.creator
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.create_time
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.modifier
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user.update_time
     *
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    private Date updateTime;


    /**
     * 用户所对应的角色id
     */
    private String roleIds;
    /**
     * 用户所对应的角色名称
     */
    private String roleNames;

    private String beginTime;
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.user_id
     *
     * @return the value of cc_user.user_id
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.user_id
     *
     * @param userId the value for cc_user.user_id
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.user_login_name
     *
     * @return the value of cc_user.user_login_name
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.user_login_name
     *
     * @param userLoginName the value for cc_user.user_login_name
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.user_name
     *
     * @return the value of cc_user.user_name
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.user_name
     *
     * @param userName the value for cc_user.user_name
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.user_password
     *
     * @return the value of cc_user.user_password
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.user_password
     *
     * @param userPassword the value for cc_user.user_password
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.user_status
     *
     * @return the value of cc_user.user_status
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public Long getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.user_status
     *
     * @param userStatus the value for cc_user.user_status
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUserStatus(Long userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.creator
     *
     * @return the value of cc_user.creator
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.creator
     *
     * @param creator the value for cc_user.creator
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.create_time
     *
     * @return the value of cc_user.create_time
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.create_time
     *
     * @param createTime the value for cc_user.create_time
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.modifier
     *
     * @return the value of cc_user.modifier
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.modifier
     *
     * @param modifier the value for cc_user.modifier
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user.update_time
     *
     * @return the value of cc_user.update_time
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user.update_time
     *
     * @param updateTime the value for cc_user.update_time
     * @mbggenerated Mon Aug 15 22:46:30 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    public String getRoleIds() {
        return roleIds;
    }

    public void setRoleIds(String roleIds) {
        this.roleIds = roleIds;
    }

    public String getRoleNames() {
        return roleNames;
    }

    public void setRoleNames(String roleNames) {
        this.roleNames = roleNames;
    }


    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }


}